### ISSUE TITLE
Melhorar a descrição do projeto...

### ISSUE THREAD

**Issue by ftonato** [thiagopaiva99/laravel-admin-generator#1]
Ao acessar o projeto, a primeira coisa que fui procurar, depois de ler a descrição, foi com qual licença rodava esse projeto, e não encontrei destacado no rodapé.

Percebi qual era pois vi o arquivo depois, mas julgo isso importante para outros contribuidores.

**Comment by thiagopaiva99** [comment]
Verdade, tinha me esquecido de por a licença, já fiz o mesmo, aproveitei e dei uma arrumada em algumas coisas do README, ainda tenho muita coisa para colocar nesse README...
Vou manter a issue aberta por enquanto para eu lembrar de terminar esse README, thanks!!

**Comment by ftonato** [comment]
- [x] Adicionar licença de uso ao readme
- [ ] Melhorar a descrição do readme

**Comment by ftonato** [comment]
Podemos abrir novamente a _issue_ se necessário.

Fico a disposição!
