### ISSUE TITLE
Adicionar url de exemplo

### ISSUE THREAD

**Issue by ftonato** [thiagopaiva99/laravel-admin-generator#2]
Fala @thiagopaiva99, beleza?

Estava pensando, se existisse uma página com a qual fosse possível interagir com o sistema funcionando e/ou um vídeo mostrando seu uso básico, seria bastante interessante para todos que querem conhecer e/ou contribuir...

**Comment by thiagopaiva99** [comment]
E man! Claro, já estava providenciando isso, estou gravando um video de demonstração!

**Comment by ftonato** [comment]
Podemos abrir novamente a _issue_ se necessário.

Fico a disposição!
